export const SIGNUP_ERROR_MESSAGES = {
  NAME_REQUIRED: '이름을 입력해주세요.',
  NICKNAME_REQUIRED: '닉네임을 입력해주세요.',
  NICKNAME_LENGTH: '닉네임은 2글자 이상 10글자 이하로 입력해주세요.',
  NICKNAME_CHECK_REQUIRED: '닉네임 중복확인이 필요합니다.',
  NICKNAME_DUPLICATED: '이미 사용 중인 닉네임입니다.',
  NICKNAME_NOT_ALLOWED:
    '닉네임은 2~10자 이내로 설정해야 하며, 특수문자는 . _ - 만 사용할 수 있습니다.',
  NICKNAME_CHECK_FAILED: '닉네임 중복 확인에 실패했습니다.',
  NAME_MIN_LENGTH: '이름을 2자 이상 입력해주세요.',
  PASSWORD_REQUIRED: '비밀번호를 입력해주세요.',
  PASSWORD_INVALID: '비밀번호가 올바르지 않습니다.',
  PASSWORD_MISMATCH: '비밀번호가 일치하지 않습니다.',
  EMAIL_REQUIRED: '이메일을 입력해주세요.',
  EMAIL_INVALID: '올바른 이메일을 입력해주세요.',
  EMAIL_DUPLICATED: '이미 사용 중인 이메일입니다.',
  EMAIL_CHECK_REQUIRED: '이메일 인증이 필요합니다.',
  PHONE_REQUIRED: '휴대폰 번호를 입력해주세요.',
  PHONE_INVALID: '올바른 휴대폰 번호를 입력해주세요.',
  PHONE_DUPLICATED: '이미 사용 중인 휴대폰 번호입니다.',
  PHONE_CHECK_REQUIRED: '휴대폰 번호 인증이 필요합니다.',
  PHONE_CHECK_FAILED: '휴대폰 번호 중복 확인에 실패했습니다.',
  VERIFICATION_CODE_REQUIRED: '인증번호를 입력해주세요.',
  VERIFICATION_CODE_MISMATCH: '인증번호가 일치하지 않습니다.',
  VERIFICATION_CODE_CHECK_FAILED: '인증번호 확인에 실패했습니다.',
  EMAIL_SEND_FAILED: '이메일 발송에 실패했습니다.',
  SELECT_REQUIRED: '생년월일을 모두 입력해주세요.',
} as const
