export const inKoreanData = {
  balance: '잔고',
  principal: '원금',
  cumulativeTransactionAmount: '누적 거래 금액',
  operationPeriod: '운용 기간',
  startDate: '시작 일자',
  endDate: '종료 일자',
  daysSincePeakUpdate: '고점 갱신 후 경과일',
  cumulativeProfitAmount: '누적 수익 금액',
  cumulativeProfitRate: '누적 수익률',
  maxCumulativeProfitAmount: '최대 누적 수익 금액',
  maxCumulativeProfitRate: '최대 누적 수익률',
  averageProfitLossAmount: '평균 손익 금액',
  averageProfitLossRate: '평균 손익률',
  maxDailyProfitAmount: '최대 일 수익 금액',
  maxDailyProfitRate: '최대 일 수익률',
  maxDailyLossAmount: '최대 일 손실 금액',
  maxDailyLossRate: '최대 일 손실률',
  roa: '자산 수익률',
  profitFactor: 'Profit Factor',
  currentDrawdown: '현재 자본 인하 금액',
  currentDrawdownRate: '현재 자본 인하율',
  maxDrawdown: '최대 자본 인하 금액',
  maxDrawdownRate: '최대 자본 인하율',
  totalTradeDays: '총 거래 일수',
  totalProfitableDays: '총 이익 일수',
  totalLossDays: '총 손실 일수',
  currentConsecutiveLossDays: '현재 연속 손실 일수',
  maxConsecutiveProfitDays: '최대 연속 이익 일수',
  maxConsecutiveLossDays: '최대 연속 손실 일수',
  winRate: '승률',
  assetManagement: '자산 및 운영 정보',
  profitLoss: '손익률 관련 정보',
  ddMddInfo: 'DD&MDD 정보',
  tradingInfo: '거래 관련 정보',
} as const
